### ISSUE TITLE
Ability to Filter Data

### ISSUE THREAD

**Issue by chanon** [hrzndhrn/xema#105]
This looks like a very promising (and greatly needed) JSON Schema library for Elixir.

There is one feature though that I have been looking for in schema validation libraries, and that is the ability to "filter" data.

What this means is that, if the input has additional properties that do not exist in the schema, then they will be removed. This might be another method called `filter` and would return a tuple with one element being the "filtered" resulting data.

Please see example from the `ajv`  library:
https://github.com/epoberezkin/ajv#filtering-data

**Comment by NickNeck** [comment]
I am not sure if this is a needed feature. Maybe it is too much "magic." In the linked description, is a note that shows some problematic points of this feature.

Can you give me a use case for this feature?

**Comment by chanon** [comment]
There are many uses, for example, if I have a REST API that accepts structured JSON as input and saves it to a PostgresQL JSONB column. 

I want whatever saved to that column to strictly match a schema. 

So with this "filter" (or you could put it in as an option to "cast") method, it would remove any additional properties that are present in the input, but not present in the schema.

Doing this in the schema validator is very convenient as nested objects may also have additional properties and the validator already has to go through each nested object.

There is only one problematic case of the feature as noted and it applies only when using together with anyOf/oneOf options which isn't that common, and there is a clean workaround.

**Comment by chanon** [comment]
Another use case is, when there is an input JSON that contains data for multiple operations, but each operation wants only a subset of the data. 

With different schemas the single source data can be filtered for each operation.

Filtering the data to remove extranous properties can help with security (eg. not letting users modify fields they are not supposed to) and memory and bandwidth usage (reducing size of messages that are being sent between elixir processes and nodes)

**Comment by NickNeck** [comment]
Thank you for your contributions.

I will add the filter as an option in `Xema.cast`.
```elixir
Xema.cast(schema, data, additionals: :keep) # as default
Xema.cast(schema, data, additionals: :remove)
```
I am not sure if this comes with 0.9.0 or 0.9.X.

**Comment by chanon** [comment]
Wonderful! Thank you so much.

**Comment by NickNeck** [comment]
The use of the filter/delete options has changed a little bit. It has to be called like this:
```
Xema.cast(schema, data, additional_properties: :delete)
```
For now, some examples can be found at [test/xema/cast/delete_test.exs](https://github.com/hrzndhrn/xema/blob/master/test/xema/cast/delete_test.exs).
`Xema` handles this feature a little bit different as `ajv`, especially for schemas with "unexpected" behavior.
