### ISSUE TITLE
Ability to Coerce Data

### ISSUE THREAD

**Issue by chanon** [hrzndhrn/xema#106]
This allows for example to specify expected schema to be numbers, and when the input is a number that is in string form, it will convert and output the result as a number allowing it to pass validation.

Please see example from `ajv` library:
https://github.com/epoberezkin/ajv#coercing-data-types

This together with the ability to filter data (#105 ) can really help speed up development time.

**Comment by NickNeck** [comment]
Hello @chanon ,

this feature will be in the next version. You can have a preview at [docs/cast.md](https://github.com/hrzndhrn/xema/blob/master/docs/cast.md)

**Comment by chanon** [comment]
That's awesome, thanks!
