### ISSUE TITLE
How can I require that at least one property is required in a map ?

### ISSUE THREAD

**Issue by lud** [hrzndhrn/xema#116]
All in the title :)

I have a bunch of properties for a map, and my application needs that at least one is defined, or any number of them except zero.

Thank you

**Comment by NickNeck** [comment]
Hello, you can use `min_properties` and `max_properties` to validate the size of a map. In your case you need something like:
```elixir
Xema.new({:map, min_properties: 1})}
```
See: https://github.com/hrzndhrn/xema/blob/master/test/suite/draft7/min_properties_test.exs

**Comment by lud** [comment]
Thank you, didn't think of it ! with `additional_properties: false` it is perfect.
