### ISSUE TITLE
https://petstore3.swagger.io/api/v3/openapi.yaml can't be validated with current xema

### ISSUE THREAD

**Issue by dergraf** [hrzndhrn/xema#123]
Validating the openapi definition from the swagger petstore https://petstore3.swagger.io/api/v3/openapi.yaml results in the following function clause error.

 (FunctionClauseError) no function clause matching in Xema.Validator.unique/2
    (xema) lib/xema/validator.ex:585: Xema.Validator.unique(%Xema.Schema{items: %Xema.Schema{}, min_items: 1, type: :list, unique_items: false}, ["placed", "approved", "delivered"])
    (xema) lib/xema/validator.ex:120: Xema.Validator.validate_by/4
    (xema) lib/xema/validator.ex:87: Xema.Validator.do_properties/4
    (xema) lib/xema/validator.ex:139: Xema.Validator.validate_by/4
    (xema) lib/xema/validator.ex:87: Xema.Validator.validate/3
    (xema) lib/xema/validator.ex:82: anonymous fn/4 in Xema.Validator.do_one_of/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (xema) lib/xema/validator.ex:415: Xema.Validator.one_of/3

**Comment by NickNeck** [comment]
Thanks for reporting. I will take a look.

**Comment by dergraf** [comment]
Thanks, that was fast! Happy to contribute a PR the next time myself! Cheers.
