### ISSUE TITLE
Possible to provide multiple possible versions of decimal?

### ISSUE THREAD

**Issue by smoes** [hrzndhrn/xema#138]
This is not really a bug. When we updated the version of xema, we ran into a conflict with other dependencies concerning the `decimal` dependency. The version was changed in `b3c8cfa0e5a3efc474c4064cf70d18b8c5bbe4e7`

`decimal` is a widely used dependency and not all libraries are at 2.0 yet. Other libraries solve this problem by providing multiple possible versions, as in https://github.com/michalmuskala/jason/blob/master/mix.exs#L30

Would that be possible or would a lower version (in Xema it was 1.7) break the code?

**Comment by NickNeck** [comment]
I will have a look at it in the evening.

**Comment by NickNeck** [comment]
Thanks for the hint. Version 0.13.4 is released.

**Comment by smoes** [comment]
That's awesome, thank you!
