### ISSUE TITLE
Cast to boolean not working as expected

### ISSUE THREAD

**Issue by sarat1669** [hrzndhrn/xema#145]
When a string is passed, it should be cast to boolean.
But it isn't

```elixir
iex> %{"type" => "boolean"} |> Xema.from_json_schema |> Xema.cast("true")
{:error,
 %Xema.CastError{
   error: nil,
   key: nil,
   message: nil,
   path: [],
   required: nil,
   to: :boolean,
   value: "true"
 }}
```

Works for integer though
```elixir
iex> %{"type" => "integer"} |> Xema.from_json_schema |> Xema.cast("1")   
{:ok, 1}
```

**Comment by NickNeck** [comment]
Thanks for reporting that. I will take a look and fix it.

**Comment by sarat1669** [comment]
As per the tests, the check seems to be added explicitly. Is there any specific reason?
https://github.com/hrzndhrn/xema/blob/dd2a6c2bffcad5392017ffef01f28058e8e8b43e/test/xema/cast/boolean_test.exs#L23-L31

**Comment by NickNeck** [comment]
Hi @sarat1669,

>  As per the tests, the check seems to be added explicitly. Is there any specific reason?

I asked myself the same question. 😉 
But now I think the expectation that `"true"` and `"false"` are cast to `true` and `false` is ok.

**Comment by sarat1669** [comment]
Cool. Thanks for fixing it
