### ISSUE TITLE
Schema with optional Struct, ie Struct or nil

### ISSUE THREAD

**Issue by garret-smith** [hrzndhrn/xema#147]
Thank you for Xema!  It's helped me a lot with JSON -> Elixir struct conversion & validation.

I'm building a rather deep schema with Xema structs referencing other Xema structs.  I'm stuck trying to create a schema with a field that is optional, ie a valid Struct or `nil`.  Example (failing) test case:

```
defmodule Baz do
  use Xema

  xema do
    field :a, [:integer, nil], default: 1
  end
end

test "multiple types with nil works with string" do
  schema = Xema.new([:string, nil])
  assert Xema.valid?(schema, "test")
  assert Xema.valid?(schema, nil)
end
test "multiple types with nil should work with struct" do
  schema = Xema.new([Baz, nil])
  assert Xema.valid?(schema, %{"a" => 2})
  assert Xema.valid?(schema, nil)
end
```

**Comment by garret-smith** [comment]
Once those basics are working, I'm hoping to use it like this:
```
defmodule Foo do
  use Xema

  xema do
    field :a, :string
    field :b, :integer
  end
end

defmodule Bar do
  use Xema

  xema do
    field :maybe_foo, [Foo, nil]
    field :title, :string
  end
end
```

Thank you for your attention.  If I can help with implementation / testing / docs please let me know.  I tried putting together a PR but got a little lost in the macro code.

**Comment by NickNeck** [comment]
Hi @garret-smith , thanks for using `xema` and your report.

The problem is that multiple types in a list are only expect basic types. That means valid values are `[ :any, :atom, :boolean, false, :float, :integer, :keyword, :list, :map, nil, :number, :string, :struct, true, :tuple]`.

The solution is to use `one_of`.
```elixir
iex(1)> defmodule Baz do
...(1)>   use Xema
...(1)>
...(1)>   xema do
...(1)>     field :a, [:integer, nil], default: 1
...(1)>   end
...(1)> end
iex(2)> schema = Xema.new(one_of: [Baz, nil])
iex(3)> Xema.valid?(schema, %Baz{a: 1})
true
iex(4)> Xema.valid?(schema, nil)
true
iex(5)> Xema.valid?(schema, 1)
false
```

Your second example should work with the code below. Unfortuanlly it doesn't but I will take a look into the code to fix it.
```elixir
defmodule Foo do
  use Xema

  xema do
    field :a, :string
    field :b, :integer
  end
end

defmodule Bar do
  use Xema

  xema do
    field :maybe_foo, Foo, allow: nil
    field :title, :string
  end
end
```

**Comment by NickNeck** [comment]
Hi @garret-smith ,

I hope the `allow: nil` will work for you.
I am thinking about extending the field macro to allow multiple xema-structs and types. So that we can also write something like this:
```elixir
  xema do
    field :prop, [Foo, Bar, nil]
  end
```

Have a nice weekend.
