### ISSUE TITLE
Inconsistency between any_of and one_of

### ISSUE THREAD

**Issue by jtrees** [hrzndhrn/xema#155]
I'm getting some unexpected behaviour when using `any_of` and `one_of`. I want to have a schema that allows a list of items where all items are of one type or another. Additionally, it should allow an empty list.

First I tried building it with `one_of` but couldn't get it to support empty lists. Using `any_of` instead works... But it doesn't really make sense to me.

Am I misunderstanding something here?

#### Examples

```elixir
# Allows an empty list.
any_of([
  list(items: strux(Foo)),
  list(items: strux(Bar))
])

# Doesn't allow an empty list.
one_of([
  list(items: strux(Foo)),
  list(items: strux(Bar))
])
```

**Comment by NickNeck** [comment]
Hi @jtrees 

To validate against `one_of`, the given data must be valid against exactly one of the given subschemas. An empty list is valid against both subschemas and therefore not valid against `one_of`. In case of `any_of` one or more subschemas had to be valid and the empty list is valid for both subschemas.

**Comment by jtrees** [comment]
Ah, thanks. I was aware of the distinction but obviously didn't think it through.
