### ISSUE TITLE
Casting is broken with required string keys

### ISSUE THREAD

**Issue by xadhoom** [hrzndhrn/xema#159]
While casting from a json schema (using `from_json_schema`), we encountered cast errors with required properties. Validation works properly.

A narrowed down example follows:

Given the schema:
```elixir
%Xema{
  refs: %{},
  schema: %Xema.Schema{
    additional_properties: false,
    properties: %{
      "bar" => %Xema.Schema{items: %Xema.Schema{type: :string}, type: :list},
      "foo" => %Xema.Schema{type: :string}
    },
    required: #MapSet<["bar", "foo"]>,
    type: :map
  }
}
```
The following casting fails:
```elixir
iex> Xema.cast(x, %{"bar" => ["hello"], "foo" => "Bob"} )                                              
{:error,
 %Xema.CastError{
   error: nil,
   key: nil,
   message: nil,
   path: [],
   required: ["bar", "foo"],
   to: :map,
   value: %{"bar" => ["hello"], "foo" => "Bob"}
 }}
```

If the xema is hand built using atom keys, like:
```elixir
%Xema{
  refs: %{},
  schema: %Xema.Schema{
    additional_properties: false,
    properties: %{
      bar: %Xema.Schema{items: %Xema.Schema{type: :string}, type: :list},
      foo: %Xema.Schema{type: :string}
    },
    required: #MapSet<[:bar, :foo]>,
    type: :map
  }
}
```
```elixir
iex> s = %{bar: ["hello"], foo: "Bob"}        
%{bar: ["hello"], foo: "Bob"}
iex> Xema.cast(x, s)                  
{:ok, %{bar: ["hello"], foo: "Bob"}}
```

Works. so seems there's something with string keys that are always "strings" when creating a xema from a json schema.

**Comment by xadhoom** [comment]
Additional note: seems ok on 0.14.0

**Comment by xadhoom** [comment]
I think the issue is there: https://github.com/hrzndhrn/xema/commit/6f7fd072ee638340f021c7fc230bd732c49bfdd8#diff-62c8c42ff87b362b70528d3f32d8e9eec2fd3ec16ce8aa3dcf20c34d77934fbdR952 where when the keys are not specified it force a default of `:atoms` which explains why it works with atom keys and not with string keys without the `keys` property set to `:strings`.

Maybe the `Xema.from_json_schema` should add by default the `keys: :strings` to the generated struct, in order to make the casting possible?

**Comment by NickNeck** [comment]
Thank you for the report. I will take a look. Maybe it takes some days, sorry for that.

**Comment by NickNeck** [comment]
Thanks again. I have released a new version.
