### ISSUE TITLE
Support for casting Phoenix Form params with lists encoded as maps

### ISSUE THREAD

**Issue by egze** [hrzndhrn/xema#164]
My use-case is building an HTML form for a JSON Schema at runtime and sending it to the server to validate and save to DB.

There is a problem currently with supporting nested fields for lists.

An example schema:
```json
{
  "title": "Quiz",
  "type": "object",
  "properties": {
    "questions": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "question",
          "answer"
        ],
        "properties": {
          "question": {
            "type": "string"
          },
          "answer": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

A quiz with a list of questions. A question is a combination of the actual question and a correct answer.

To represent it in a Phoenix form, the HTML would be similar to this:

```html
<form>
  <div class="question">
    <input type="text" name="quiz[questions][0][question]" value="1 + 1 = ?" />
    <input type="text" name="quiz[questions][0][answer]" value="2" />
  </div>
  <div class="question">
    <input type="text" name="quiz[questions][1][question]" value="2 + 2 = ?" />
    <input type="text" name="quiz[questions][1][answer]" value="4" />
  </div>
</form>
```

The template for adding new questions dynamically to the form would be:
```html
<div class="question">
  <input type="text" name="quiz[questions][__INDEX__][question]"  />
  <input type="text" name="quiz[questions][__INDEX__][answer]" />
</div>
```
We would append the fragment to the form and replace `__INDEX__` dynamically with JS.

OK, now we submit the form, the params would be in this shape:
```elixir
params = %{
  "quiz" => %{
    "questions" => %{
      "0" => %{"question" => "1 + 1 = ?", "answer" => "2"},
      "1" => %{"question" => "2 + 2 = ?", "answer" => "4"}
    }
  }
}
```

When working with `Ecto.Changeset`, it knows how to correctly cast such structures to the needed schema. But `Xema` would throw an error if I tried to `Xema.cast` it.

Either I'm missing a correct `Xema` usage, or the functionality to cast Phoenix params is missing.

My expectation of `Xema.cast(xema, params)` for the example above, would be:

```elixir
{:ok, %{
  "questions" => [
    %{"answer" => "2", "question" => "1 + 1 = ?"},
    %{"answer" => "4", "question" => "2 + 2 = ?"}
  ]
}}
```

**Comment by NickNeck** [comment]
Hello @egze , sorry for the late response. I'm on vacation and don't check on my projects that often.

Thank you for this issue. Your proposal looks like a good addition to `xema`. A PR is welcome. But it may be two or three weeks before I take a look.

**Comment by egze** [comment]
Cool. Can you give me some pointers about the design?

Should I just auto-cast a map into a list? There are some `do_cast` functions with guards for the data type, but how do I properly get the intended type for this particular data fragment from the schema? Is the passed schema argument already the schema for this fragment, or it is the global schema?

**Comment by NickNeck** [comment]
An extra annotations ist not necessary. There is the castable protocol in the code. You can add a function :
 ```elixir
defimpl Xema.Castable, for: Map do
  ...
  def cast(map, :list, _module, _schema) ...
end

**Comment by egze** [comment]
I gave it a go: https://github.com/hrzndhrn/xema/pull/167

But for some reason, it doesn't cast the inner-map values. See the failing test: [test/xema/cast/list_test.exs:371](https://github.com/hrzndhrn/xema/pull/167/files#diff-1301f9cc662344773c19d0681d90c09bcc218293d3256fbf7bba66180bf18c25R371)

Do you have an idea why?
