### ISSUE TITLE
Custom data with boolean values has strange behaviour

### ISSUE THREAD

**Issue by egze** [hrzndhrn/xema#165]
There seems to be a strange behaviour with boolean values.

```elixir
iex(39)> Xema.new({:string, option_with_boolean: true})
%Xema{
  refs: %{},
  schema: %Xema.Schema{
    data: %{option_with_boolean: %Xema.Schema{type: true}},
    type: :string
  }
}
```

If using anything else, for example a string literal:
```elixir
iex(40)> Xema.new({:string, option_with_boolean: "true"})
%Xema{
  refs: %{},
  schema: %Xema.Schema{data: %{option_with_boolean: "true"}, type: :string}
}
```

**Expected:**
```elixir
iex(40)> Xema.new({:string, option_with_boolean: true})
%Xema{
  refs: %{},
  schema: %Xema.Schema{data: %{option_with_boolean: true}, type: :string}
}
```

**Comment by NickNeck** [comment]
Hello @egze 

In JSON-Schema additional properties are always allowed. In `xema` this values are saved in `:data`. The values of the additional properties could be schemas.
```elixir
Xema.new({:string, foo: :number})
%Xema{refs: %{}, schema: %Xema.Schema{data: %{foo: %Xema.Schema{type: :number}}, type: :string}}
```
The `nil`, `true` and `false` are valid schemas. See [Boolean JSON  Schemas](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.4.3.2) and [null](https://json-schema.org/understanding-json-schema/reference/null.html).

Therefore, the behavior you describe is expected.

**Comment by egze** [comment]
OK, maybe I misunderstood the purpose of custom data. In the documentation it says
> `data` none schema data.
https://github.com/hrzndhrn/xema/blob/main/lib/xema/schema.ex#L25

I thought it is a way how to have custom options in a schema. For example in the json-editor, they have custom properties.

```
{
  "type": "string",
  "format": "markdown",
  "options": {
    "simplemde": {
      "toolbar": [
        "bold",
        "italic",
        "heading",
        "|",
        "link",
        "quote",
        "|",
        "preview",
        "fullscreen",
        "guide"
      ],
      "spellChecker": false
    }
  }
}
```

I think anything passed into data, should have literal values.

**Comment by NickNeck** [comment]
Everything that is not a JsonSchema keyword goes to `data`. In the values of `data` `xema` will create schemas when possible.
```elixir
iex(1)> Xema.new(foo: true)
%Xema{refs: %{}, schema: %Xema.Schema{data: %{foo: %Xema.Schema{type: true}}}}
```
It is not recommended to put anything in `data`. The `data` key is mainly for compatibility with JsonSchema and other implementation of JsonSchema.

When you want options for a value this can be written into the schema.
```elixir
iex(1)> schema = Xema.new {:map, properties: %{
...(1)>   text: :string,
...(1)>   type: {:atom, enum: [:headline, :text, :link]}
...(1)> }}
%Xema{
  refs: %{},
  schema: %Xema.Schema{
    properties: %{
      text: %Xema.Schema{type: :string},
      type: %Xema.Schema{enum: [:headline, :text, :link], type: :atom}
    },
    type: :map
  }
}
iex(2)> Xema.cast(schema, text: "foo", type: "text")
{:ok, %{text: "foo", type: :text}}
iex(3)>
```

**Comment by egze** [comment]
Thanks for the explanation. I'll close my PR.
