### ISSUE TITLE
How to provide entire map as a parameter for custom validators?

### ISSUE THREAD

**Issue by Arsenalist** [hrzndhrn/xema#176]
I have a situation where I've defined the schema like:

```
   ...
   "bid_amount" => Xema.new(:number),
   "platform_ids" => Xema.new({:list, validator: &list_contains_valid_platform/1}),
   ....

  def list_contains_valid_platform(platform_ids) do
     ...
  end
```

However, for me to validate `platform_ids` correctly I need access to the entire Map that's being validated, not just `platform_ids` which is what the custom validator function takes. Can I access the whole map in the custom validator?

**Comment by NickNeck** [comment]
For now, that is unfortunately not supported. But it will be coming soon. 
As a workaround, you can add a validator at a point where you get all the needed data.

**Comment by Arsenalist** [comment]
Thank you. Sorry to be dense, but how do I do that? I thought validation is currently only supported at the field level (besides the if/then validator).

**Comment by NickNeck** [comment]
I am on the rush but I will give you an example tomorrow.

**Comment by NickNeck** [comment]
The promised example:
```elixir
defmodule Validator do
  import Xema.Builder

  require Logger

  @schema Xema.new(
            map(
              validator: &__MODULE__.check_multi/1,
              properties: %{
                num: number(),
                multi: number()
              }
            )
          )

  def check_multi(%{num: num, multi: multi}) do
    dbg(rem(multi,num))
    if multi > num && rem(multi, num) == 0 do
    :ok
    else
      {:error, :not_multi}
    end
  end

  def validate(data) do
    Xema.validate!(@schema, data) 
  end
end
```
```elixir
Validator.validate(%{num: 3, multi: 7})
```
```
** (Xema.ValidationError) Validator fails with :not_multi for value %{multi: 7, num: 3}.
```

**Comment by Arsenalist** [comment]
Thank you. That is very helpful - going to use it!
