### ISSUE TITLE
Inconsistency between code, docs and spec for creating atoms when loading a JSON schema

### ISSUE THREAD

**Issue by gianluca-nitti** [hrzndhrn/xema#179]
The [docs for Xema.from_json_schema/2](https://hexdocs.pm/xema/0.17.2/Xema.html#from_json_schema/2) say that the option for creating atoms for unknown keys when parsing a JSON schema is `atoms: :force`, while the example and the [code](https://github.com/hrzndhrn/xema/blob/main/lib/xema/json_schema.ex#L206) say it is `atom: :force` (singular `atom` vs plural `atoms`).

Additionally, the [`@type opts :: [draft: String.t()]`](https://github.com/hrzndhrn/xema/blob/main/lib/xema/json_schema.ex#L13) used in the `@spec to_xema(json_schema, opts) :: atom | tuple` in the same file, does not include that option, making tools such as dialyzer fail when it is used.

**Comment by NickNeck** [comment]
Thank you for reporting this. I will have a look.

**Comment by NickNeck** [comment]
A new release is out. Thanks again.

**Comment by gianluca-nitti** [comment]
Thank you for fixing!
